### PR TITLE
Rancher documentation

### PR DESCRIPTION
**Pull request by abdenour-drif**
added documentation on how to use 3 pipelines to manage rancher env
1- how to manage the scratch env
2- how to create backend module 
3- how to create UI

### CODE REVIEW

**Comment by dcrossleyau** [comment]
I see that the pictures are not displaying in the generated documentation of the branch. (Follow the "Show all checks" from this PR page, then use the Search system to find it.)

I will investigate that on my tomorrow.

**Review by wafschneider — COMMENTED** [review]
The instructions seem clear to me. I know that @funkymalc will be testing them today, helping the Thor team. I'll await his feedback and @dcrossleyau before approving. Thanks, Abdenour!

**Review by funkymalc — APPROVED** [review]
I've followed the instructions on building a new stripes bundle and was successful.

**Review by dcrossleyau — APPROVED** [review]
Thanks Abdenour, this is very useful. Obviously lots of work to achieve this desciption and the facilities.

Getting the Markdown formatting layout and display is difficult for such documents. I made various adjustments, and viewed them locally as i went. I made the changes in separate commits with explanations.

**Comment by dcrossleyau** [comment]
Published at:
https://dev.folio.org/faqs/how-to-get-started-with-rancher/#manage-scratch-environment
and the subsequent two sections.

**Pull request merged**
