### PR TITLE
FOLIO-2601 New doc getting started Rancher

### PR DESCRIPTION
**Pull request by dcrossleyau**

### CODE REVIEW

**Comment by dcrossleyau** [comment]
I have done another round of editing, following your last set of commits.

Before we merge this, i intend to move it to the "Guides" section. It has become way too much for an FAQ.

**Comment by dcrossleyau** [comment]
@celticmask Your changes today seem to have clobbered my changes from earlier today.

**Comment by dcrossleyau** [comment]
Regarding my comment above about previous commits (f5bdaad and 0a4c89a and 4147764) being inexplicably lost:
I made those same changes again today.

**Comment by dcrossleyau** [comment]
@celticmask There seems to be some problem with your git technique. There are now conflicts in this file.

**Comment by celticmask** [comment]
Want to create latest changes with new PR

**Pull request closed without merging**
