### PR TITLE
Add Nightmare usage guide.

### PR DESCRIPTION
**Pull request by OleksandrAntonenko1**
Duplication of WIKI: https://wiki.folio.org/display/COMMUNITY/Personal+Nightmare

### CODE REVIEW

**Comment by funkymalc** [comment]
@dcrossleyau - Can you review and possibly merge this PR?

**Comment by dcrossleyau** [comment]
I am investigating this. There will be some changes needed.

**Comment by OleksandrAntonenko1** [comment]
Thank you for merging and your changes. All instructions are fine cause I have tried to run them recently. It is a new article so it is up to date.

**Comment by dcrossleyau** [comment]
I followed the top section of the instructions, but only the initial two tests (login and configure) were successful, and the rest failed. What VM are you testing against?

**Comment by OleksandrAntonenko1** [comment]
This documentation contains instruction more how to run tests. So there are maybe changes that break tests, cause I have the same problem. So if you can run them according(and see that they are failing) to my instructions my article is correct. I will create a bug ar story to fix this.

**Pull request merged**
